apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f compose.yaml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: go-app
  name: go-app
spec:
  type: LoadBalancer
  ports:
    - name: go-app-local-kube
      port: 4000
      targetPort: 3000
  selector:
    io.kompose.service: go-app
