// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package psql

import (
	"time"
)

type Book struct {
	ID        int64
	Title     string
	Author    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
