version: "3.8"

services:
  kc_postgres:
    image: postgres:15.7
    volumes:
      - kc_psql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - keycloak_net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: start-dev
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://kc_postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      # KC_HOSTNAME_STRICT_BACKCHANNEL: false
      # KC_HTTP_ENABLED: true
      # KC_HOSTNAME_STRICT_HTTPS: false
      # KC_HEALTH_ENABLED: true
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - kc_postgres
    networks:
      - keycloak_net

volumes:
  kc_psql_data:
    driver: local

networks:
  keycloak_net:
    driver: bridge
